// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2srrn3QfejUEPR2ae5oLxPbz4l9MctE',
    appId: '1:825926580367:web:d3f0098ad21f46314e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    authDomain: 'catat-a4880.firebaseapp.com',
    storageBucket: 'catat-a4880.appspot.com',
    measurementId: 'G-DN5Q052X1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3kjinwDXMO9ELYuAt0AJSa8p9jEn1nk',
    appId: '1:825926580367:android:748d8d0b0aae8c2f4e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    storageBucket: 'catat-a4880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8djBzObtQ-iWbctp0Lf9pjOJKElNUqhg',
    appId: '1:825926580367:ios:a1a1c74801f161a94e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    storageBucket: 'catat-a4880.appspot.com',
    iosClientId: '825926580367-8m58vbil8ag2dcrchqrtg9ds3rdojo1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.catatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8djBzObtQ-iWbctp0Lf9pjOJKElNUqhg',
    appId: '1:825926580367:ios:443f88628e2cf7124e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    storageBucket: 'catat-a4880.appspot.com',
    iosClientId: '825926580367-jabhrv5e40hcpudqq1dcm1f5r37fokdo.apps.googleusercontent.com',
    iosBundleId: 'com.fakhrif.catatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2srrn3QfejUEPR2ae5oLxPbz4l9MctE',
    appId: '1:825926580367:web:93bf431c09070ce84e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    authDomain: 'catat-a4880.firebaseapp.com',
    storageBucket: 'catat-a4880.appspot.com',
    measurementId: 'G-2QXQK1SVFD',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDv2srrn3QfejUEPR2ae5oLxPbz4l9MctE',
    appId: '1:825926580367:web:551fd99265011b0d4e58fa',
    messagingSenderId: '825926580367',
    projectId: 'catat-a4880',
    authDomain: 'catat-a4880.firebaseapp.com',
    storageBucket: 'catat-a4880.appspot.com',
    measurementId: 'G-PJ1DSD8SH5',
  );
}
